[project]
name = "a2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=3.2.0",
    "huggingface-hub>=0.27.1",
    "pillow>=11.1.0",
    "scikit-learn>=1.6.1",
    "unsloth>=2025.1.6",
    "wandb>=0.19.4",
]
